version: "3.3"
services:
  microservice_name:
    build: .
    image: microservice_name/flask:1.0
    ports:
      - 5000:5000
    environment:
      - SECRET_KEY="the_secret_key_from_docker_compose"
      - DEBUG="True"
    volumes:
      - .:/app # This volume is only usefull during development!